In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("data.csv")
data.head()

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0               4.0         No                      4.0            6.0   
1               9.0        Yes                      0.0            0.0   
2               9.0        Yes                      1.0            2.0   
3               0.0         No                      6.0            7.0   
4               3.0         No                      9.0            4.0   

  Drained_after_socializing  Friends_circle_size  Post_frequency Personality  
0                        No                 13.0             5.0   Extrovert  
1                       Yes                  0.0             3.0   Introvert  
2                       Yes                  5.0             2.0   Introvert  
3                        No                 14.0             8.0   Extrovert  
4                        No                  8.0             5.0   Extrovert

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           2837 non-null   float64
 1   Stage_fear                 2827 non-null   object 
 2   Social_event_attendance    2838 non-null   float64
 3   Going_outside              2834 non-null   float64
 4   Drained_after_socializing  2848 non-null   object 
 5   Friends_circle_size        2823 non-null   float64
 6   Post_frequency             2835 non-null   float64
 7   Personality                2900 non-null   object 
dtypes: float64(5), object(3)
memory usage: 181.4+ KB


In [6]:
data.columns

Index(['Time_spent_Alone', 'Stage_fear', 'Social_event_attendance',
       'Going_outside', 'Drained_after_socializing', 'Friends_circle_size',
       'Post_frequency', 'Personality'],
      dtype='object')

In [7]:
for c in data.columns : 
    if (data[c].dtype == 'O'):
        data[c] = data[c].fillna(data[c].mode()[0])
    else:
        data[c] = data[c].fillna(data[c].mean())

In [8]:
data['Stage_fear'].dtype # gives dtype of this perticular column

dtype('O')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           2900 non-null   float64
 1   Stage_fear                 2900 non-null   object 
 2   Social_event_attendance    2900 non-null   float64
 3   Going_outside              2900 non-null   float64
 4   Drained_after_socializing  2900 non-null   object 
 5   Friends_circle_size        2900 non-null   float64
 6   Post_frequency             2900 non-null   float64
 7   Personality                2900 non-null   object 
dtypes: float64(5), object(3)
memory usage: 181.4+ KB


In [10]:
# removing blank spaces from front and back in column names : 
data.columns = [col.strip() for col in data.columns]  # .strip will remove unwanted spaces from begining and ending of the column names

In [11]:
data.head()

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0               4.0         No                      4.0            6.0   
1               9.0        Yes                      0.0            0.0   
2               9.0        Yes                      1.0            2.0   
3               0.0         No                      6.0            7.0   
4               3.0         No                      9.0            4.0   

  Drained_after_socializing  Friends_circle_size  Post_frequency Personality  
0                        No                 13.0             5.0   Extrovert  
1                       Yes                  0.0             3.0   Introvert  
2                       Yes                  5.0             2.0   Introvert  
3                        No                 14.0             8.0   Extrovert  
4                        No                  8.0             5.0   Extrovert

In [12]:
X = data.drop('Personality', axis=1)
y = data["Personality"].values

In [13]:
X

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0                  4.0         No                      4.0            6.0   
1                  9.0        Yes                      0.0            0.0   
2                  9.0        Yes                      1.0            2.0   
3                  0.0         No                      6.0            7.0   
4                  3.0         No                      9.0            4.0   
...                ...        ...                      ...            ...   
2895               3.0         No                      7.0            6.0   
2896               3.0         No                      8.0            3.0   
2897               4.0        Yes                      1.0            1.0   
2898              11.0        Yes                      1.0            3.0   
2899               3.0         No                      6.0            6.0   

     Drained_after_socializing  Friends_circle_size  Post_frequency  
0                           No                 13.0             5.0  
1                          Yes                  0.0             3.0  
2                          Yes                  5.0             2.0  
3                           No                 14.0             8.0  
4                           No                  8.0             5.0  
...                        ...                  ...             ...  
2895                        No                  6.0             6.0  
2896                        No                 14.0             9.0  
2897                       Yes                  4.0             0.0  
2898                       Yes                  2.0             0.0  
2899                        No                  6.0             9.0  

[2900 rows x 7 columns]

In [14]:
y

array(['Extrovert', 'Introvert', 'Introvert', ..., 'Introvert',
       'Introvert', 'Extrovert'], dtype=object)

In [15]:
X

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0                  4.0         No                      4.0            6.0   
1                  9.0        Yes                      0.0            0.0   
2                  9.0        Yes                      1.0            2.0   
3                  0.0         No                      6.0            7.0   
4                  3.0         No                      9.0            4.0   
...                ...        ...                      ...            ...   
2895               3.0         No                      7.0            6.0   
2896               3.0         No                      8.0            3.0   
2897               4.0        Yes                      1.0            1.0   
2898              11.0        Yes                      1.0            3.0   
2899               3.0         No                      6.0            6.0   

     Drained_after_socializing  Friends_circle_size  Post_frequency  
0                           No                 13.0             5.0  
1                          Yes                  0.0             3.0  
2                          Yes                  5.0             2.0  
3                           No                 14.0             8.0  
4                           No                  8.0             5.0  
...                        ...                  ...             ...  
2895                        No                  6.0             6.0  
2896                        No                 14.0             9.0  
2897                       Yes                  4.0             0.0  
2898                       Yes                  2.0             0.0  
2899                        No                  6.0             9.0  

[2900 rows x 7 columns]

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Encode categorical variables in X using one-hot encoding
X_encoded = pd.get_dummies(X, drop_first=True)

# Encode target variable y if it's categorical

le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split the data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.2, random_state=42)

# Feature scaling (optional but recommended for many ML models)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
# training logestic regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Predicting on the test set
y_pred = model.predict(X_test_scaled)
# Evaluating the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
lra = f"Accuracy: {accuracy * 100:.2f}%"

Accuracy: 91.90%


In [18]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[278,  24],
       [ 23, 255]], dtype=int64)

In [22]:
# KNN Model

In [23]:
# training knn classification model :
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train_scaled,y_train)
# predicting on test set :
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
knna = f"Accuracy: {accuracy * 100:.2f}%"


Accuracy: 92.24%


In [24]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[276,  26],
       [ 19, 259]], dtype=int64)

In [25]:
# SVM model

In [26]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')
# fitting model
model.fit(X_train_scaled,y_train)
# predicting on test_set : 
y_pred = model.predict(X_test_scaled)
# 

In [27]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
svca = f"Accuracy: {accuracy * 100:.2f}%"

Accuracy: 92.93%


In [28]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[278,  24],
       [ 17, 261]], dtype=int64)

In [29]:
# naive bayes model : 
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
# fitting model : 
model.fit(X_train_scaled,y_train)
# predicting output and testing accuracy
y_pred = model.predict(X_test_scaled)


In [30]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
nbaa = f"Accuracy: {accuracy * 100:.2f}%"

Accuracy: 92.93%


In [31]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[278,  24],
       [ 17, 261]], dtype=int64)

In [32]:
# decission tree classification model training:

In [33]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
# fitting/training model : 
model.fit(X_train_scaled,y_train)
# predicting output and testing accuracy : 
y_pred = model.predict(X_test_scaled)

In [34]:
accuracy = accuracy_score(y_test, y_pred)
dta = f"Accuracy: {accuracy * 100:.2f}%"

In [35]:
dta

'Accuracy: 86.90%'

In [36]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[262,  40],
       [ 36, 242]], dtype=int64)

In [37]:
# random forest classification model training:

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
# fitting training model : 
model.fit(X_train_scaled,y_train)
# predicting output and testing accuracy :
y_pred = model.predict(X_test_scaled)

In [39]:
accuracy = accuracy_score(y_test,y_pred)
rfca = dta = f"Accuracy: {accuracy * 100:.2f}%"

In [40]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[277,  25],
       [ 19, 259]], dtype=int64)

In [41]:
# showing highest and lowest accuracy
accuracies = {
    'LogisticRegression' : lra,
    'KNN':knna,
    'SVM':svca,
    'Naive_bayes' : nbaa,
    'decision tree' : dta,
    'random forest' : rfca
}

best_model = max(accuracies,key=accuracies.get)
worse_model = min(accuracies,key=accuracies.get)

print(f"Best model = {best_model} with accuracy {accuracies[best_model]}")
print(f"worse model = {worse_model} with accuracy {accuracies[worse_model]}")

Best model = SVM with accuracy Accuracy: 92.93%
worse model = LogisticRegression with accuracy Accuracy: 91.90%
